services:
  app:
    image: dino2_docker
    environment:
      HOST_UID: $(id -u)
      HOST_GID: $(id -g)
      PYTHONUNBUFFERED: 1  # Disable output buffering
    volumes:
      - type: bind
        # source: ./../HyperWorkspace/HyperImages/LIB-HSI
        source: ./../HyperImages/LIB-HSI
        target: /workspaces/LIB-HSI
        consistency: cached
      - type: bind
        source: ./
        target: /workspaces/hsi_ss
        consistency: cached
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    shm_size: 80g #8g
    # command: sudo /usr/bin/python3 /workspaces/dinov2/notebooks/base_hsi_lightning.py
    tty: true  # Enable TTY
    stdin_open: true  # Keep stdin open
    runtime: nvidia
    